spring:
  profiles:
    active: local
  application:
    name: headless
  main:
    allow-circular-references: true
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
s2:
  item:
    value:
      date:
        start: 200