server:
  port: 9080
  compression:
    enabled: true
    min-response-size: 1024
    mime-types: application/javascript,application/json,application/xml,text/html,text/xml,text/plain,text/css,image/*

spring:
  profiles:
    active: ${S2_DB_TYPE:mysql-local}
#    active: ${S2_DB_TYPE:mysql-prod}
  application:
    name: chat
  config:
    import:
#      - classpath:s2-config-prod.yaml
      - classpath:s2-config-local.yaml
      - optional:classpath:custom-config.yaml
  main:
    allow-circular-references: true
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB

mybatis:
  mapper-locations=classpath:mappers/custom/*.xml,classpath*:/mappers/*.xml

logging:
  level:
    dev.langchain4j: DEBUG
    dev.ai4j.openai4j: DEBUG

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
  packages-to-scan: com.tencent.supersonic
  paths-to-match: /api/chat/**,/api/semantic/**

knife4j:
  enable: true
  openapi:
    title: 'SuperSonic API Documentation'
    description: 'SuperSonic API Documentation'
    version: v1.0
  setting:
    language: zh-CN
#  basic:
#    enable: true
#    username: test
#    password: 123456#
  documents:
    default:
      title: ChatBI API Documents
      description: ChatBI API Documents

bi:
  tts:
    base-path: /data/nfs/easybi/elephant-screen/upload/video/tts
    base-url: https://dc.migu.cn/elephant-screen/upload/video/tts
